#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <rpm/rpmlog.h>
#include <rpm/rpmlib.h>
#include <rpm/rpmstring.h>
#include "build/mfs.h"

#define FINDDEBUGINFO "%{_rpmconfigdir}/find-debuginfo.sh "\
	    "%{?_missing_build_ids_terminate_build:--strict-build-id} "\
	    "%{?_include_minidebuginfo:-m} "\
	    "%{?_find_debuginfo_dwz_opts} "\
	    "%{?_find_debuginfo_opts} \"%{_builddir}/%{?buildsubdir}\" %{nil}"

rpmRC setupPkgFunc(MfsContext context)
{
    rpmRC rc = RPMRC_FAIL;
    MfsSpec spec = mfsContextGetSpec(context);
    MfsBTScript install_script = NULL;
    MfsPackage pkg = NULL;
    MfsFileLines flines;
    MfsFileFiles ffiles;
    char *arch = mfsSpecGetArch(spec);
    char *expanded;

    if (!spec) {
	mfslog_err("Cannot get spec from context\n");
	goto exit;
    }

    if (!rpmExpandNumeric("%{_enable_debug_packages}"))
	goto exit_success;  // Debug packages are disabled

    // Check the arch of the package
    if (arch && !strcmp(arch, "noarch")) {
	mfslog_info("Debuginfo subpackage won't be generated by module - noarch package\n");
	goto exit_success;  // Noarch packages shouldn't have debuginfo sub-packages
    }

    // Modify %install script to strip debuginfo and gen filelist
    install_script = mfsSpecGetScript(spec, MFS_SPEC_SCRIPT_INSTALL);
    expanded = rpmExpand(FINDDEBUGINFO, NULL);
    mfsBTScriptAppendLine(install_script, expanded);
    free(expanded);
    mfsSpecSetScript(spec, install_script, MFS_SPEC_SCRIPT_INSTALL);

    // Prepare subpackage
    mfslog_info("Adding debuginfo subpackage\n");
    pkg = mfsPackageNew(context, "debuginfo2",
			"Debug information for package %{name}",
			MFS_PACKAGE_FLAG_SUBNAME);
    if (!pkg)
	goto exit;

    mfsPackageSetDescription(pkg,
	"This package provides debug information for package %{name}.\n"
	"Debug information is useful when developing applications that use this\n"
	"package or when debugging this package.\n", NULL);
    mfsPackageSetTag(pkg, RPMTAG_GROUP, "Development/Debug", NULL);
    mfsPackageSetTag(pkg, RPMTAG_AUTOREQPROV, "0", NULL);

    if (mfsPackageFinalize(pkg) != RPMRC_OK)
	goto exit;

    flines = mfsPackageGetFileLines(pkg);
    mfsFileLinesAppend(flines, "%defattr(-,root,root)");
    mfsPackageSetFileLines(pkg, flines);
    mfsFileLinesFree(flines);

    ffiles = mfsPackageGetFileFiles(pkg);
    mfsFileFilesAppend(ffiles, "debugfiles.list");
    mfsPackageSetFileFiles(pkg, ffiles);
    mfsFileFilesFree(ffiles);

exit_success:
    rc = RPMRC_OK;
exit:
    mfsPackageFree(pkg);
    mfsBTScriptFree(install_script);
    free(arch);
    mfsSpecFree(spec);
    return rc;
}

rpmRC init_debuginfomodule(MfsManager mm)
{
    MfsBuildHook buildhook;
    buildhook = mfsBuildHookNew(setupPkgFunc, MFS_HOOK_POINT_POSTPARSE);
    mfsBuildHookSetPrettyName(buildhook, "setupPkgFunc()");
    mfsManagerRegisterBuildHook(mm, buildhook);
    return RPMRC_OK;
}
